# Generated by Django 4.2 on 2023-04-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('short_code', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Secrets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField()),
                ('secret', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=25)),
                ('destination_url', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateField()),
            ],
        ),
    ]
