# Generated by Django 4.2 on 2023-04-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hits',
            new_name='Hit',
        ),
        migrations.RenameModel(
            old_name='Secrets',
            new_name='Secret',
        ),
        migrations.RenameModel(
            old_name='Urls',
            new_name='Url',
        ),
    ]
